services:

  # FastAPI application


  # Nginx Service


  # PostgreSQL Service (PGVector)
  pgvector:

    image: pgvector/pgvector:0.8.2-pg18-trixie
  
    container_name: pgvector
  
    ports:
      - "5432:5432"
  
    volumes:
      - pgvector_data:/var/lib/postgresql
  
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  
    env_file:
      - ./env/.env.postgres
  
    networks:
      - backend
  
    restart: always
  
    healthcheck:
      test: ["CMD_SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Qdrant Service
  qdrant:

    image: qdrant/qdrant:v1.18

    container_name: qdrant

    ports:
      - "6333:6333"
      - "6334:6334"

    volumes:
      - qdrant_data:/qdrant/storage

    networks:
      - backend

    restart: always
    

  # Prometheus Monitoring 


  # Grafana Dashboard


  # Node Exporter for system Metrics


  # PostgreSQL Exporter for Postgres Metrics
  postgres_exporter:
  
    image: prometheuscommunity/postgres-exporter:v0.19.1
  
    container_name: postgres-exporter
  
    ports:
      - "9187:9187"
  
    env_file:
      - ./env/.env.postgres-exporter
  
    depends_on:
      - pgvector

    networks:
      - backend

    restart: always