services:
  mongodb:
    image: mongo:latest 
    container_name: mongodb
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    networks:
      - backend
    restart: always

networks:
  backend: